[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.111.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.111.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.111.3"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.111.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/npmjs/*"
to = "/npmjs/"
status = 200

[[redirects]]
  from = "https://lunchbag.ca/lunch-money-new-era"
  to = "https://lunchmoney.app/blog/the-new-era?utm_source=personal-blog&utm_medium=post&utm_campaign=the_new_era"
  status = 301
  force = true

[[redirects]]
  from = "lunch-money-we-lowered-our-pricing"
  to = "https://lunchmoney.app/blog/we-lowered-our-pricing?utm_source=personal-blog&utm_medium=post&utm_campaign=we_lowered_our_pricing"
  status = 301
  force = true